version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  app:
    image: node:14
    container_name: my_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydb
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run start:dev"
    volumes:
      - .:/app
